monolog:
    channels: ['deprecation']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        sentry:
            type: sentry
            level: info
            hub_id: Sentry\State\HubInterface
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [404, 405]
                channels: ["!event"]

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: error
            stream:
                type: stream
                path: php://stderr
                level: debug
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
